# Generated by Django 3.0.2 on 2020-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bloodtype',
            fields=[
                ('blood', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('quant', models.FloatField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('aadhar', models.IntegerField(unique=True)),
                ('blood', models.CharField(max_length=3)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=3)),
                ('quantity', models.FloatField()),
                ('by', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('orderdate', models.DateField()),
                ('shipdate', models.DateField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood', models.CharField(max_length=3)),
                ('quantity', models.FloatField()),
                ('by', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('orderdate', models.DateField()),
                ('shipdate', models.DateField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='yadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=100)),
            ],
        ),
    ]
